using Microsoft.AspNetCore.Mvc;
using ModernCRM.Crm.Api.Frontend;
namespace ModernCRM.Crm.Api.Controllers;
[ApiController,Route("api/activities")]
public sealed class ActivitiesController(FrontendCrmStore store):ControllerBase
{
 [HttpGet] public IActionResult GetAll(int page=1,int pageSize=20,string? sortBy=null,bool sortDesc=false,string? search=null,string? type=null,string? isCompleted=null){lock(store.SyncRoot){var t=FrontendApi.Tenant(User);var q=store.Activities.Where(x=>x.TenantId==t&&!x.IsDeleted);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>FrontendApi.Contains(x.Subject,search)||FrontendApi.Contains(x.Description,search)||FrontendApi.Contains(x.ContactName,search));if(!string.IsNullOrWhiteSpace(type))q=q.Where(x=>x.Type.Equals(type,StringComparison.OrdinalIgnoreCase));if(bool.TryParse(isCompleted,out var completed))q=q.Where(x=>x.IsCompleted==completed);return Ok(FrontendApi.Page(q,page,pageSize,sortBy,sortDesc));}}
 [HttpGet("{id:int}")] public IActionResult Get(int id){lock(store.SyncRoot){var x=store.Activities.FirstOrDefault(x=>x.Id==id&&x.TenantId==FrontendApi.Tenant(User)&&!x.IsDeleted);return x is null?NotFound():Ok(x);}}
 [HttpPost] public IActionResult Create(ActivityPayload r){lock(store.SyncRoot){if(string.IsNullOrWhiteSpace(r.Subject))return BadRequest(new{message="Subject is required."});var x=new ActivityModel{Id=store.NextId(),TenantId=FrontendApi.Tenant(User),Subject=r.Subject,Type=r.Type??"Task",Description=r.Description,ContactId=r.ContactId,DueDate=r.DueDate,IsCompleted=r.IsCompleted??false};Enrich(x);store.Activities.Add(x);return CreatedAtAction(nameof(Get),new{id=x.Id},x.Id);}}
 [HttpPut("{id:int}")] public IActionResult Update(int id,ActivityPayload r){lock(store.SyncRoot){var x=store.Activities.FirstOrDefault(x=>x.Id==id&&x.TenantId==FrontendApi.Tenant(User)&&!x.IsDeleted);if(x is null)return NotFound();x.Subject=r.Subject;x.Type=r.Type??x.Type;x.Description=r.Description;x.ContactId=r.ContactId;x.DueDate=r.DueDate;x.IsCompleted=r.IsCompleted??x.IsCompleted;Enrich(x);return NoContent();}}
 [HttpDelete("{id:int}")] public IActionResult Delete(int id){lock(store.SyncRoot){var x=store.Activities.FirstOrDefault(x=>x.Id==id&&x.TenantId==FrontendApi.Tenant(User)&&!x.IsDeleted);if(x is null)return NotFound();x.IsDeleted=true;return NoContent();}}
 private void Enrich(ActivityModel x){var c=store.Contacts.FirstOrDefault(c=>c.Id==x.ContactId&&!c.IsDeleted);x.ContactName=c is null?null:$"{c.FirstName} {c.LastName}".Trim();}
}