using Microsoft.AspNetCore.Mvc;
using ModernCRM.Crm.Api.Frontend;
namespace ModernCRM.Crm.Api.Controllers;
[ApiController,Route("api/opportunities")]
public sealed class OpportunitiesController(FrontendCrmStore store):ControllerBase
{
 [HttpGet] public IActionResult GetAll(int page=1,int pageSize=20,string? sortBy=null,bool sortDesc=false,string? search=null,string? stage=null){lock(store.SyncRoot){var t=FrontendApi.Tenant(User);var q=store.Opportunities.Where(x=>x.TenantId==t&&!x.IsDeleted);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>FrontendApi.Contains(x.Title,search)||FrontendApi.Contains(x.AccountName,search));if(!string.IsNullOrWhiteSpace(stage))q=q.Where(x=>x.Stage.Equals(stage,StringComparison.OrdinalIgnoreCase));return Ok(FrontendApi.Page(q,page,pageSize,sortBy,sortDesc));}}
 [HttpGet("{id:int}")] public IActionResult Get(int id){lock(store.SyncRoot){var x=store.Opportunities.FirstOrDefault(x=>x.Id==id&&x.TenantId==FrontendApi.Tenant(User)&&!x.IsDeleted);return x is null?NotFound():Ok(x);}}
 [HttpPost] public IActionResult Create(Payload r){lock(store.SyncRoot){if(string.IsNullOrWhiteSpace(r.Title))return BadRequest(new{message="Title is required."});var x=new OpportunityModel{Id=store.NextId(),TenantId=FrontendApi.Tenant(User),Title=r.Title,Value=r.Value,Stage=r.Stage??"Prospecting",AccountId=r.AccountId,ContactId=r.ContactId,AssignedToUserId=r.AssignedToUserId,ExpectedCloseDate=r.ExpectedCloseDate,Notes=r.Notes};Enrich(x);store.Opportunities.Add(x);return CreatedAtAction(nameof(Get),new{id=x.Id},x.Id);}}
 [HttpPut("{id:int}")] public IActionResult Update(int id,Payload r){lock(store.SyncRoot){var x=store.Opportunities.FirstOrDefault(x=>x.Id==id&&x.TenantId==FrontendApi.Tenant(User)&&!x.IsDeleted);if(x is null)return NotFound();x.Title=r.Title;x.Value=r.Value;x.Stage=r.Stage??x.Stage;x.AccountId=r.AccountId;x.ContactId=r.ContactId;x.AssignedToUserId=r.AssignedToUserId;x.ExpectedCloseDate=r.ExpectedCloseDate;x.Notes=r.Notes;Enrich(x);return NoContent();}}
 [HttpDelete("{id:int}")] public IActionResult Delete(int id){lock(store.SyncRoot){var x=store.Opportunities.FirstOrDefault(x=>x.Id==id&&x.TenantId==FrontendApi.Tenant(User)&&!x.IsDeleted);if(x is null)return NotFound();x.IsDeleted=true;return NoContent();}}
 private void Enrich(OpportunityModel x){x.AccountName=store.Accounts.FirstOrDefault(a=>a.Id==x.AccountId&&!a.IsDeleted)?.Name;var c=store.Contacts.FirstOrDefault(c=>c.Id==x.ContactId&&!c.IsDeleted);x.ContactName=c is null?null:$"{c.FirstName} {c.LastName}".Trim();}
 public sealed record Payload(string? Title,decimal Value,string? Stage,DateTime? ExpectedCloseDate,string? Notes,int? AccountId,int? ContactId,int? AssignedToUserId);
}