namespace AuthService.Domain.Entities;

/// <summary>
/// Represents a deployed CRM API instance. Each instance has its own database
/// and can host multiple tenants. The Id is a GUID generated by the CRM service
/// itself on first startup and written into its appsettings.json.
/// </summary>
public class ServiceInstance
{
    public Guid     Id          { get; set; }
    public string   Name        { get; set; } = default!;
    public string   ApiUrl      { get; set; } = default!;
    public string?  Description { get; set; }
    public bool     IsActive    { get; set; } = true;
    public bool     IsDeleted   { get; set; }
    public DateTime CreatedAt   { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt  { get; set; }

    public ICollection<Tenant> Tenants { get; set; } = new List<Tenant>();
}
